name: Token Deploy to Heroku

on:
  push:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: Release Token Provider API
      url: https://baygon-token-provider.herokuapp.com/swagger-ui/index.html
    steps:
    - uses: actions/checkout@v2
    - name: Release Token Provider API
      uses: akhileshns/heroku-deploy@v3.12.12
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: "baygon-token-provider"
        heroku_email: ${{secrets.HEROKU_API_KEY}}
        healthcheck: "https://baygon-token-provider.herokuapp.com/actuator/health"
        appdir: "TokenProvider"
