name: MyMusic Deploy to Heroku

on:
  push:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: Release MyMusic API
      url: https://baygon-mymusic.herokuapp.com/swagger-ui/index.html
    steps:
    - uses: actions/checkout@v2
    - name: Release MyMusic API
      uses: akhileshns/heroku-deploy@v3.12.12
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: "baygon-mymusic"
        heroku_email: ${{secrets.HEROKU_API_KEY}}
        healthcheck: "https://baygon-mymusic.herokuapp.com/actuator/health"
        appdir: "MyMusic"
